config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

    resources :questions do
      resources :answers, only: [:index, :new, :create]
    end
  end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates_presence_of :question_id, :description
  validates :description, length: { minimum: 50 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers

  validates_presence_of :title, :description
  validates :title, length: { minimum: 20 }
  validates :description, length: { minimum: 50 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @question = Question.find(params[:question_id])
    @answers = Answer.order(updated_at: :desc)
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    @errors =[]
  end

  def create
    @question = Question.find_by(id: params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question = @question

    if @answer.save
      redirect_to @question, notice: 'Answer was successfully created.'
    else
      @answers = @question.answers
      @errors = @answer.errors.full_messages
      render '/questions/show'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:description)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.order(updated_at: :desc)
  end

  def show
    @question = Question.find_by(id: params[:id])
    @answers = @question.answers
    @answer = Answer.new
    @errors = []
  end

  def new
    @question = Question.new
    @errors =[]
  end

  def edit
    @question = Question.find(params[:id])
    @errors = []
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      @errors = @question.errors.full_messages
      render :edit
    end
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Question was successfully created.'
    else
      @errors = @question.errors.full_messages
      render :new
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @answers = @question.answers
    @question.destroy
    @answers.each do |answer|
      answer.destroy
    end

    redirect_to questions_path, notice: 'Article Deleted'
  end

  private

  def question_params
    params.require(:question).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMission</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>
<% if @errors != [] %>
   <ul class="error">
     <% @errors.each do |error| %>
      <h3><%= error %></h3>
      <% end %>
   </ul>
 <% end %>


<%= form_for @question do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="questions"><span class="questions-q">R</span>escue Mission</h1>
<ul id="questions-list">
  <% @questions.each do |question| %>
    <li>
        <h3><%= link_to question.title, question %></h3>
    </li>
  <% end %>
</ul>
<h3 class='ask'><%= link_to 'Ask a Question', new_question_path %><h3>

app/views/questions/new.html.erb
<h1 class="new-q">New Question</h1>
<% if @errors != [] %>
   <ul class="error">
     <% @errors.each do |error| %>
      <h3><%= error %></h3>
      <% end %>
   </ul>
 <% end %>


<%= form_for(@question) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_area :title, :size => 50 %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => 50  %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

<h1 class="back-button"><%= link_to 'Back', questions_path %></h1>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="q--">
<h1><%= @question.title %></h1>
</div>
<div class="a--">
<p><%= @question.description %></p>
</div>

<div class="edit-delete">
  <%= link_to 'Edit Question', edit_question_path(@question) %>
  <%= link_to 'Delete Article', question_path(@question), method: :delete, data: {confirm: 'Are you sure?'} %>
</div>

<% if @errors != [] %>
  <ul class="error">
    <% @errors.each do |error| %>
      <h3><%= error %></h3>
    <% end %>
  </ul>
<% end %>

<%= form_for [@question, @answer] do |f| %>
  <div class="field">
    <%= f.label :Answer_the_Question %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<div class="wrapper">
<h1>Answers</h1>
<ul id="answers-list">
  <% @answers.each do |answer| %>
    <li class="-answers">
        <%= answer.description %>
    </li>
  <% end %>
</ul>
</div>

<div class="back-page"><%= link_to 'Back', questions_path %></div>